
name: hugo CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies # fix npm imcompatibility with lockfileVersion@2
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci # This command is similar to npm install, except it's meant to be used in automated environments such as test platforms, continuous integration, and deployment.
      
      - name: Build
        run: hugo --minify # minify HTML, CSS, and JavaScript

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # default: gh-pages
          publish_dir: ./public
          destination_dir: docs # By default, existing files in the publish branch (or only in destination_dir if given) will be removed.
          commit_message: ${{ github.event.head_commit.message }}
