
name: hugo CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Install postcss-cli
        run: |
          npm install postcss-cli

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: demo # default: gh-pages
          publish_dir: ./public
          destination_dir: docs # By default, existing files in the publish branch (or only in destination_dir if given) will be removed.
          commit_message: ${{ github.event.head_commit.message }}
